// src/data/questions.js

export const stages = [
  {
    id: 'discovery',
    label: 'Discovery',
    icon: '🔍',
    color: '#3b82f6',
    tagline: 'Understand the problem',
    description: "We'll explore the core problem you're solving and who really has it.",
  },
  {
    id: 'market',
    label: 'Market',
    icon: '🌍',
    color: '#10b981',
    tagline: 'Know your landscape',
    description: "Who else is out there? What's your edge?",
  },
  {
    id: 'feasibility',
    label: 'Feasibility',
    icon: '⚡',
    color: '#f59e0b',
    tagline: 'Can you actually do it?',
    description: "Let's be honest about your resources, timeline, and what's realistic.",
  },
  {
    id: 'gtm',
    label: 'Go-to-Market',
    icon: '🚀',
    color: '#8b5cf6',
    tagline: "How you'll win",
    description: "Who's your first customer, and how will you reach them?",
  },
];

export const questions = [
  // ─── DISCOVERY ───────────────────────────────────────────────
  {
    id: 'projectName',
    stage: 'discovery',
    order: 1,
    type: 'text',
    emoji: '✨',
    question: "What's the name of your idea or project?",
    subtext: "Don't overthink this — you can change it later. Just give it a working name.",
    tooltip: "A working name helps you think of this as a real thing, not just an idea. It can be anything — even a placeholder.",
    placeholder: "e.g. Farmlink, BoltPay, QuickDoc...",
    required: true,
  },
  {
    id: 'problemStatement',
    stage: 'discovery',
    order: 2,
    type: 'textarea',
    emoji: '😤',
    question: "What frustration or problem are you trying to fix?",
    subtext: "The best products solve problems that make people say 'Why doesn't this exist yet?' Describe the pain in plain words.",
    tooltip: "Don't describe your solution — describe the problem. Pretend you're explaining it to your grandmother. The more specific, the better.",
    placeholder: "e.g. Small farmers in rural Nigeria can't easily connect to buyers in cities. They spend hours calling around and still sell at unfair prices...",
    required: true,
    hint: { icon: '💡', text: "Tip: The best problem statements include WHO suffers, WHAT they suffer, and WHEN it happens." }
  },
  {
    id: 'targetUser',
    stage: 'discovery',
    order: 3,
    type: 'textarea',
    emoji: '👤',
    question: "Describe your ideal first customer in vivid detail.",
    subtext: "Not 'everyone'. Not 'SMEs'. One specific person — their name, job, daily struggle, and why they desperately need this.",
    tooltip: "Great products are built for someone specific, not everyone. The more precisely you describe this person, the easier everything becomes — your product, your marketing, your pitch.",
    placeholder: "e.g. Amaka, 34, runs a tailoring shop in Enugu. She gets 60% of her orders via WhatsApp but loses track of them. She has a smartphone but uses only basic apps...",
    required: true,
  },
  {
    id: 'whyNow',
    stage: 'discovery',
    order: 4,
    type: 'select',
    emoji: '⏰',
    question: "Why is NOW the right time for this?",
    subtext: "Great timing isn't luck — it's insight. What's changed in the world that makes this possible or urgent right now?",
    tooltip: "Investors and early adopters often ask this. It could be new technology (AI, mobile money), regulation change, pandemic aftermath, a generation coming of age, or infrastructure improving.",
    required: true,
    options: [
      { value: 'tech_shift', label: '📱 New technology just made it possible', desc: 'Mobile internet, AI, fintech rails, etc.' },
      { value: 'behavior', label: '🔄 User behavior has changed recently', desc: 'People now do something they didn\'t before' },
      { value: 'regulation', label: '📋 New laws or policies opened the door', desc: 'Regulation, licensing, or gov programs' },
      { value: 'pain_grown', label: '📈 The problem has gotten bigger or more visible', desc: 'More people feel it now than before' },
      { value: 'market_gap', label: '🕳️ A competitor left the market or failed', desc: 'There\'s an obvious gap nobody is filling' },
      { value: 'personal', label: '💪 I have a unique skill/access others don\'t', desc: 'My positioning creates a window of opportunity' },
      { value: 'other', label: '🌀 Something else', desc: 'I\'ll explain below' },
    ],
  },
  {
    id: 'whyNowDetail',
    stage: 'discovery',
    order: 5,
    type: 'textarea',
    emoji: '📝',
    question: "Say more about the timing — what's your unfair advantage?",
    subtext: "What do you know, have access to, or can do that others can't easily copy?",
    tooltip: "Unfair advantages could be: network/community access, deep domain expertise, existing user relationships, proprietary data, technology partnerships, or lived experience that gives you unique insight.",
    placeholder: "e.g. I've spent 5 years in logistics and know all the major depot owners personally. I also built a chatbot in university so I understand the tech...",
    required: false,
  },

  // ─── MARKET ──────────────────────────────────────────────────
  {
    id: 'existingSolutions',
    stage: 'market',
    order: 6,
    type: 'textarea',
    emoji: '🔭',
    question: "What do people currently do to solve this problem?",
    subtext: "Before your product exists, how are they coping? Even bad workarounds tell you a lot.",
    tooltip: "This reveals your real competition. People paying for bad solutions means they want a solution. People doing nothing means you may need to create demand — much harder.",
    placeholder: "e.g. They use Excel spreadsheets, WhatsApp groups, or just call each other. Some hire assistants to manage it manually...",
    required: true,
    hint: { icon: '🎯', text: "Note: If nobody does anything about this problem, that's a warning sign — not a green light." }
  },
  {
    id: 'competitors',
    stage: 'market',
    order: 7,
    type: 'textarea',
    emoji: '🥊',
    question: "Who else is trying to solve this? Name them.",
    subtext: "Search Google, App Store, and local startup lists before answering. No competition usually means no market.",
    tooltip: "Naming competitors is a sign of maturity — not weakness. It shows you've done your homework. Describe what they do well and where they fall short.",
    placeholder: "e.g. Farmcrowdy tackles investment, Thrive Agric does offtake. Neither focuses on real-time price discovery between small farmers and local buyers...",
    required: false,
  },
  {
    id: 'differentiation',
    stage: 'market',
    order: 8,
    type: 'textarea',
    emoji: '💎',
    question: "What will make your version meaningfully better or different?",
    subtext: "Not 'better UI' or 'cheaper'. What structural advantage means they can't easily copy you?",
    tooltip: "Think in terms of: speed, trust, local knowledge, network effects, proprietary data, unique distribution, or business model. 'Better design' is not a moat.",
    placeholder: "e.g. We'll start in Kano where I grew up and have relationships with 200+ farmers. We'll use WhatsApp which they already use — no new app download needed...",
    required: true,
  },
  {
    id: 'marketSize',
    stage: 'market',
    order: 9,
    type: 'select',
    emoji: '📊',
    question: "How big is the market you're targeting — roughly?",
    subtext: "This is about the total pool of people or businesses with this problem.",
    tooltip: "You don't need a 100-page market research report. A rough honest estimate is better than a made-up $50 billion figure. Think about: how many people have this problem, and how often.",
    required: true,
    options: [
      { value: 'local', label: '🏘️ Local / Community', desc: 'A specific city, campus, or neighborhood' },
      { value: 'national', label: '🇳🇬 National (one country)', desc: 'All of Nigeria or another single country' },
      { value: 'regional', label: '🌍 Regional (multiple African countries)', desc: 'West Africa, Pan-Africa, etc.' },
      { value: 'global', label: '🌐 Global', desc: 'The problem exists everywhere in the world' },
    ],
  },

  // ─── FEASIBILITY ─────────────────────────────────────────────
  {
    id: 'teamSize',
    stage: 'feasibility',
    order: 10,
    type: 'select',
    emoji: '👥',
    question: "Who's building this with you?",
    subtext: "Investors say they invest in teams, not ideas. Even for solo projects, knowing your gaps matters.",
    tooltip: "Be honest. A solo founder with no technical skills building a complex app faces a very different journey than a team of 3 with complementary skills.",
    required: true,
    options: [
      { value: 'solo', label: '🦸 Just me', desc: 'Solo founder, doing everything' },
      { value: 'small', label: '👯 2–3 people', desc: 'Small founding team' },
      { value: 'medium', label: '🤝 4–8 people', desc: 'Larger team, some specialists' },
      { value: 'large', label: '🏢 9+ people', desc: 'Organization with departments' },
    ],
  },
  {
    id: 'techCapability',
    stage: 'feasibility',
    order: 11,
    type: 'select',
    emoji: '💻',
    question: "What's your team's technical ability?",
    subtext: "This helps us recommend the right tools and flag risks early.",
    tooltip: "No technical skill doesn't mean you can't build — it just changes how you build. No-code tools can get you surprisingly far. We'll tailor the plan to where you are.",
    required: true,
    options: [
      { value: 'none', label: '🙋 No technical skills', desc: 'Can use apps, can\'t build them' },
      { value: 'basic', label: '🔧 Basic technical skills', desc: 'Some coding, familiar with tools' },
      { value: 'intermediate', label: '⚙️ Moderate technical skills', desc: 'Can build simple apps/websites' },
      { value: 'advanced', label: '🚀 Strong technical team', desc: 'Full-stack dev, can build anything' },
    ],
  },
  {
    id: 'timeline',
    stage: 'feasibility',
    order: 12,
    type: 'select',
    emoji: '📅',
    question: "When do you need a working first version?",
    subtext: "Your MVP — something real users can try. Not perfect, just testable.",
    tooltip: "MVP = Minimum Viable Product. It's the simplest thing that lets real users test whether your core idea works. Most good MVPs are built in 4–12 weeks.",
    required: true,
    options: [
      { value: 'now', label: '⚡ Immediately (under 2 weeks)', desc: 'Urgent — hackathon, competition, demo' },
      { value: 'month', label: '🗓️ Within a month', desc: '2–4 weeks' },
      { value: 'quarter', label: '📆 This quarter (1–3 months)', desc: 'Reasonable pace' },
      { value: 'halfyear', label: '🌱 6 months', desc: 'Building carefully' },
      { value: 'year', label: '🏗️ Over a year', desc: 'Complex product, long runway' },
      { value: 'flexible', label: '🌊 No fixed deadline', desc: 'Exploring, no pressure' },
    ],
  },
  {
    id: 'budget',
    stage: 'feasibility',
    order: 13,
    type: 'select',
    emoji: '💰',
    question: "What budget do you have to build the first version?",
    subtext: "Be honest — this shapes every recommendation we make.",
    tooltip: "Bootstrapped isn't bad — it forces creativity. Many great African startups started on nothing. But your budget determines what's realistic right now.",
    required: true,
    options: [
      { value: 'zero', label: '🔥 Zero — pure hustle', desc: 'Time and skills only, no cash' },
      { value: 'micro', label: '💵 Under ₦500k (~$300)', desc: 'Shoestring budget' },
      { value: 'small', label: '💳 ₦500k – ₦2M (~$300–$1,200)', desc: 'Small but workable' },
      { value: 'medium', label: '💰 ₦2M – ₦10M (~$1,200–$6,000)', desc: 'Decent runway' },
      { value: 'funded', label: '🏦 Over ₦10M ($6,000+)', desc: 'Funded or well-capitalized' },
    ],
  },
  {
    id: 'biggestRisk',
    stage: 'feasibility',
    order: 14,
    type: 'textarea',
    emoji: '⚠️',
    question: "What keeps you up at night about this project?",
    subtext: "Name your biggest fear or uncertainty. The things you don't say here are the things that kill projects.",
    tooltip: "Every great founder has a list of things that could go wrong. The best ones say them out loud and build a plan to address each one. What's yours?",
    placeholder: "e.g. I'm not sure people will pay for this. I'm worried the technical build will take too long. My co-founder and I haven't tested working together under stress...",
    required: false,
  },

  // ─── GO-TO-MARKET ─────────────────────────────────────────────
  {
    id: 'firstCustomer',
    stage: 'gtm',
    order: 15,
    type: 'textarea',
    emoji: '🎯',
    question: "Who is the ONE person or organisation that will be your very first paying customer?",
    subtext: "Not a category — a real human or a real company. Do you already know them?",
    tooltip: "The best early-stage strategy is to find one real customer before you've built anything. If you can't name a specific person, your market understanding is still too abstract.",
    placeholder: "e.g. Alhaji Musa who owns 3 poultry farms in Kaduna — I already know him and he's complained about this exact problem to me twice...",
    required: true,
  },
  {
    id: 'acquisitionChannel',
    stage: 'gtm',
    order: 16,
    type: 'select',
    emoji: '📣',
    question: "How will you reach your first 100 customers?",
    subtext: "Pick your primary channel — the one you'll focus on first.",
    tooltip: "Most startups fail at distribution, not product. Pick one channel and go deep rather than spreading thin across all of them.",
    required: true,
    options: [
      { value: 'personal', label: '🤝 Personal network & referrals', desc: 'Friends, family, existing contacts' },
      { value: 'community', label: '🌐 Online communities & WhatsApp groups', desc: 'Where your users already hang out' },
      { value: 'social', label: '📱 Social media (Instagram, TikTok, X)', desc: 'Content, ads, influencer partnerships' },
      { value: 'partnerships', label: '🤝 Partnerships & B2B sales', desc: 'Work with organisations that serve your users' },
      { value: 'events', label: '🎪 Events, markets, or physical outreach', desc: 'Show up where customers are in person' },
      { value: 'seo', label: '🔍 Search / SEO / Content marketing', desc: 'People searching for solutions online' },
      { value: 'agents', label: '🚶 Field agents or on-ground team', desc: 'Feet on the ground in local markets' },
    ],
  },
  {
    id: 'revenueModel',
    stage: 'gtm',
    order: 17,
    type: 'select',
    emoji: '💸',
    question: "How will you make money (or sustain this)?",
    subtext: "Pick the model that fits your situation best.",
    tooltip: "Even nonprofits need a sustainability model. Being clear on how you generate value and capture some of it is critical — even in MVP stage.",
    required: true,
    options: [
      { value: 'subscription', label: '🔄 Monthly/annual subscription', desc: 'SaaS model — recurring payments' },
      { value: 'transaction', label: '💳 Per-transaction fee', desc: 'Take a small cut of each transaction' },
      { value: 'freemium', label: '🆓 Free + paid premium features', desc: 'Free base, charge for more' },
      { value: 'one_time', label: '💰 One-time purchase or license', desc: 'Pay once to use' },
      { value: 'ads', label: '📢 Advertising', desc: 'Free for users, paid by advertisers' },
      { value: 'b2b', label: '🏢 B2B — sell to businesses', desc: 'Companies pay for access for their staff/customers' },
      { value: 'grant', label: '🤲 Grant / NGO / Government funded', desc: 'Donor-funded model' },
      { value: 'unsure', label: '🤔 Not sure yet', desc: 'Still figuring this out' },
    ],
  },
  {
    id: 'successMetric',
    stage: 'gtm',
    order: 18,
    type: 'textarea',
    emoji: '📈',
    question: "In 90 days, what single number would tell you this is working?",
    subtext: "One metric. Not 10. The one thing that, if it goes up, means everything is working.",
    tooltip: "This is your North Star metric. For a marketplace, it might be 'transactions per week'. For a SaaS, 'weekly active users'. For an e-commerce, 'repeat purchase rate'. Pick the one that most directly shows value is being created.",
    placeholder: "e.g. 50 farmers completing at least one sale through the platform. Or: ₦1M in transactions processed. Or: 200 active users who open the app 3+ times per week...",
    required: true,
  },
];

export const totalQuestions = questions.length;
export const stageQuestions = (stageId) => questions.filter(q => q.stage === stageId);
