// src/data/tools.js

export const toolCategories = [
  {
    id: 'nocode',
    label: 'No-Code',
    icon: '🧩',
    color: '#10b981',
    tagline: 'Build without writing code',
    description: 'These tools let you create real products — apps, websites, databases — without a developer. Perfect if you\'re a non-technical founder.',
    tools: [
      {
        name: 'Bubble',
        icon: '🫧',
        category: 'Web App Builder',
        useFor: 'Full web applications with logic, database, and user accounts',
        notFor: 'Simple landing pages or native mobile apps',
        cost: 'Free plan available. Paid from $29/mo',
        nigeriaNote: 'Works great in Nigeria. Many Nigerian startups launched on Bubble.',
        link: 'https://bubble.io',
        rating: 5,
        learningCurve: 'Medium (1–2 weeks to get productive)',
      },
      {
        name: 'Webflow',
        icon: '🌊',
        category: 'Website Builder',
        useFor: 'Beautiful, professional websites and landing pages',
        notFor: 'Complex app logic or user-generated content at scale',
        cost: 'Free plan. Paid from $14/mo',
        nigeriaNote: 'Excellent for startup landing pages and marketing sites.',
        link: 'https://webflow.com',
        rating: 5,
        learningCurve: 'Medium (requires understanding of CSS concepts)',
      },
      {
        name: 'Glide',
        icon: '✨',
        category: 'Mobile App Builder',
        useFor: 'Data-driven mobile apps built from Google Sheets',
        notFor: 'Complex logic or offline-heavy apps',
        cost: 'Free for basic. Paid from $25/mo',
        nigeriaNote: 'Works well on Android which dominates in Nigeria.',
        link: 'https://glideapps.com',
        rating: 4,
        learningCurve: 'Easy (build in hours)',
      },
      {
        name: 'FlutterFlow',
        icon: '🦋',
        category: 'Mobile App Builder',
        useFor: 'Native iOS and Android apps with real Flutter code export',
        notFor: 'Teams with no design sense — needs some UI thinking',
        cost: 'Free plan. Paid from $30/mo',
        nigeriaNote: 'Growing community. Great if you want to eventually hand code to a developer.',
        link: 'https://flutterflow.io',
        rating: 4,
        learningCurve: 'Medium-Hard',
      },
      {
        name: 'Softr',
        icon: '🏗️',
        category: 'Web App Builder',
        useFor: 'Client portals, directories, membership sites from Airtable',
        notFor: 'Complex transactional apps',
        cost: 'Free for small teams. Paid from $49/mo',
        nigeriaNote: 'Good for B2B tools and internal dashboards.',
        link: 'https://softr.io',
        rating: 4,
        learningCurve: 'Easy',
      },
      {
        name: 'Typeform / Tally',
        icon: '📋',
        category: 'Forms & Surveys',
        useFor: 'Beautiful forms, surveys, onboarding flows — even simple MVPs',
        notFor: 'Not a full product, but great for validation',
        cost: 'Tally is free. Typeform free plan limited.',
        nigeriaNote: 'Tally.so is popular with Nigerian entrepreneurs for quick validation.',
        link: 'https://tally.so',
        rating: 5,
        learningCurve: 'Very Easy (minutes)',
      },
    ],
  },
  {
    id: 'lowcode',
    label: 'Low-Code',
    icon: '⚙️',
    color: '#3b82f6',
    tagline: 'Some coding, much faster',
    description: 'Low-code tools assume basic technical ability. They handle the heavy lifting so developers can build 5x faster than coding from scratch.',
    tools: [
      {
        name: 'Supabase',
        icon: '🟢',
        category: 'Backend / Database',
        useFor: 'Database, authentication, storage, and APIs — without backend expertise',
        notFor: 'Extremely high-scale or complex data requirements',
        cost: 'Free tier very generous. Paid from $25/mo',
        nigeriaNote: 'Used heavily by Nigerian dev community. Great documentation.',
        link: 'https://supabase.com',
        rating: 5,
        learningCurve: 'Easy for developers, hard for non-technical',
      },
      {
        name: 'Firebase',
        icon: '🔥',
        category: 'Backend / Database',
        useFor: 'Real-time apps, mobile backends, notifications',
        notFor: 'Complex relational data or SQL-heavy projects',
        cost: 'Generous free tier. Pay as you grow.',
        nigeriaNote: 'Works well in Africa. Popular with React Native and Flutter developers.',
        link: 'https://firebase.google.com',
        rating: 4,
        learningCurve: 'Medium',
      },
      {
        name: 'Retool',
        icon: '🔧',
        category: 'Internal Tools',
        useFor: 'Admin panels, dashboards, internal ops tools — quickly',
        notFor: 'Customer-facing products',
        cost: 'Free for small teams.',
        nigeriaNote: 'Great for ops teams at Nigerian startups.',
        link: 'https://retool.com',
        rating: 4,
        learningCurve: 'Medium',
      },
      {
        name: 'n8n / Make (Integromat)',
        icon: '🔄',
        category: 'Automation',
        useFor: 'Connecting apps, automating workflows without code',
        notFor: 'Core product logic',
        cost: 'n8n open source (free self-host). Make free tier available.',
        nigeriaNote: 'Excellent for automating WhatsApp, email, payment, and CRM flows.',
        link: 'https://n8n.io',
        rating: 4,
        learningCurve: 'Medium',
      },
    ],
  },
  {
    id: 'payments',
    label: 'Payments & Money',
    icon: '💳',
    color: '#f59e0b',
    tagline: 'Get paid in Nigeria and Africa',
    description: 'You need to collect money. These are the most trusted and widely used payment tools for Nigerian and African startups.',
    tools: [
      {
        name: 'Paystack',
        icon: '🟢',
        category: 'Payment Gateway',
        useFor: 'Accept card, bank transfer, USSD, and mobile money payments in Nigeria',
        notFor: 'International payments without add-on',
        cost: '1.5% per transaction + ₦100 cap',
        nigeriaNote: 'The default choice for Nigerian startups. Excellent API and support.',
        link: 'https://paystack.com',
        rating: 5,
        learningCurve: 'Easy',
      },
      {
        name: 'Flutterwave',
        icon: '🌊',
        category: 'Payment Gateway',
        useFor: 'Pan-African payments, international cards, multi-currency',
        notFor: 'Simple single-market setups (Paystack is easier for Nigeria-only)',
        cost: '1.4% per transaction',
        nigeriaNote: 'Best for multi-country African products. Trusted and well-documented.',
        link: 'https://flutterwave.com',
        rating: 5,
        learningCurve: 'Easy–Medium',
      },
      {
        name: 'Lemonsqueezy',
        icon: '🍋',
        category: 'SaaS Payments',
        useFor: 'Global subscriptions, SaaS billing, digital products',
        notFor: 'Physical goods or local Nigerian payments',
        cost: '5% + payment fees',
        nigeriaNote: 'Good for selling software/digital products globally from Nigeria.',
        link: 'https://lemonsqueezy.com',
        rating: 4,
        learningCurve: 'Easy',
      },
    ],
  },
  {
    id: 'ai_tools',
    label: 'AI & Productivity',
    icon: '🤖',
    color: '#8b5cf6',
    tagline: 'Move faster with AI',
    description: 'These AI tools can dramatically reduce your team\'s workload — from writing, design, to code generation.',
    tools: [
      {
        name: 'Claude / ChatGPT',
        icon: '🧠',
        category: 'AI Assistant',
        useFor: 'Writing, research, code, customer support templates, business plans',
        notFor: 'Replacing deep domain expertise',
        cost: 'Free tiers. Paid from $20/mo',
        nigeriaNote: 'Both accessible in Nigeria. Use for content, emails, code debugging.',
        link: 'https://claude.ai',
        rating: 5,
        learningCurve: 'Very Easy',
      },
      {
        name: 'v0 by Vercel',
        icon: '⚡',
        category: 'UI Code Generator',
        useFor: 'Generate React UI components from text descriptions',
        notFor: 'Non-technical teams (still need to deploy the code)',
        cost: 'Free tier generous',
        nigeriaNote: 'Used by Nigerian dev community to speed up frontend work.',
        link: 'https://v0.dev',
        rating: 4,
        learningCurve: 'Easy for developers',
      },
      {
        name: 'Canva',
        icon: '🎨',
        category: 'Design',
        useFor: 'Social media, pitch decks, logos, marketing materials',
        notFor: 'Complex product design (use Figma)',
        cost: 'Free. Pro from $12.99/mo',
        nigeriaNote: 'Massively popular across Nigeria. Very accessible.',
        link: 'https://canva.com',
        rating: 5,
        learningCurve: 'Very Easy',
      },
    ],
  },
];

export const decisionMatrix = [
  { scenario: "I have no technical skills and need something in 2 weeks", recommendation: "Use Tally.so for forms, WhatsApp Business for comms, and Canva for branding. Serve manually first.", tools: ['Tally', 'WhatsApp Business', 'Canva'] },
  { scenario: "I have no technical skills but 2–3 months", recommendation: "Build on Bubble or Glide. Use Paystack for payments, Supabase for your database.", tools: ['Bubble', 'Glide', 'Paystack', 'Supabase'] },
  { scenario: "I have some technical skills (basic coding)", recommendation: "Use Next.js + Supabase + Paystack. Deploy on Vercel. Use v0.dev to generate UI fast.", tools: ['Next.js', 'Supabase', 'Paystack', 'Vercel'] },
  { scenario: "I have a full technical team", recommendation: "Build custom, but use Paystack/Flutterwave for payments. Don't build auth from scratch — use Supabase or Clerk.", tools: ['Paystack', 'Supabase', 'Clerk', 'Vercel'] },
  { scenario: "I'm building a marketplace", recommendation: "Start with Flutterwave split payments. Use Bubble for MVP. Don't build the marketplace engine — use a template.", tools: ['Flutterwave', 'Bubble', 'Airtable'] },
  { scenario: "I'm building a SaaS for international customers", recommendation: "Lemonsqueezy for billing, Supabase for backend, Next.js frontend, Vercel for hosting.", tools: ['Lemonsqueezy', 'Supabase', 'Next.js', 'Vercel'] },
];
